#!/usr/bin/env python3
"""Dump a full end-to-end decode trace from our decoder via the callback system.

Produces a structured text file with one line per event. Format:
  MB mbX mbY bit=OFFSET type=TYPE
  PRED mbX mbY scan=N raster=R mode=M mpm=M
  COEFF mbX mbY scan=N nC=NC tc=TC to=TO tz=TZ bits=B levels=[...] coeffs_crc=XXXX
  DEQUANT mbX mbY scan=N crc=XXXX [dc c10 c20 c30]
  PIXEL mbX mbY scan=N pred_crc=XXXX out_crc=XXXX pred=[p0..p3] out=[o0..o3]

Usage:
    python scripts/dump_full_trace.py [fixture] [output_file]

SPDX-License-Identifier: MIT
"""
import sys


def main():
    print("This script documents the trace format.")
    print("The actual trace is generated by the C++ test.")
    print("Use: Sub0h264_Tests.exe -tc='*full trace*' -s 2>&1 > trace.txt")


if __name__ == "__main__":
    main()
