#!/usr/bin/env python3
"""Generate per-frame CRC32 reference values from ffmpeg decode.

Outputs a C++ constexpr array of expected CRC32 values for each frame
in a test fixture H.264 file. CRC is computed stride-aware over Y+U+V
planes in I420 format (same as NestNinja's validated approach).

Usage:
    python scripts/gen_reference_crcs.py tests/fixtures/baseline_640x480_short.h264

SPDX-License-Identifier: MIT
"""
import subprocess
import struct
import sys
import zlib


def compute_frame_crc(yuv_data: bytes, width: int, height: int) -> int:
    """Compute CRC32 over I420 Y+U+V planes (stride = width, no padding)."""
    y_size = width * height
    u_size = (width // 2) * (height // 2)

    crc = 0
    # Y plane
    for r in range(height):
        row = yuv_data[r * width : (r + 1) * width]
        crc = zlib.crc32(row, crc) & 0xFFFFFFFF
    # U plane
    u_offset = y_size
    for r in range(height // 2):
        row = yuv_data[u_offset + r * (width // 2) : u_offset + (r + 1) * (width // 2)]
        crc = zlib.crc32(row, crc) & 0xFFFFFFFF
    # V plane
    v_offset = y_size + u_size
    for r in range(height // 2):
        row = yuv_data[v_offset + r * (width // 2) : v_offset + (r + 1) * (width // 2)]
        crc = zlib.crc32(row, crc) & 0xFFFFFFFF

    return crc


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.h264> [max_frames]", file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    max_frames = int(sys.argv[2]) if len(sys.argv) > 2 else 9999

    # Probe dimensions
    probe = subprocess.run(
        ["ffprobe", "-v", "quiet", "-select_streams", "v:0",
         "-show_entries", "stream=width,height",
         "-of", "csv=p=0", input_file],
        capture_output=True, text=True
    )
    width, height = map(int, probe.stdout.strip().split(","))
    frame_size = width * height * 3 // 2  # I420

    # Decode all frames to raw YUV
    proc = subprocess.Popen(
        ["ffmpeg", "-i", input_file, "-f", "rawvideo", "-pix_fmt", "yuv420p",
         "-v", "quiet", "-"],
        stdout=subprocess.PIPE
    )

    crcs = []
    frame_idx = 0
    while frame_idx < max_frames:
        data = proc.stdout.read(frame_size)
        if len(data) < frame_size:
            break
        crc = compute_frame_crc(data, width, height)
        crcs.append(crc)
        frame_idx += 1

    proc.wait()

    # Output as C++ constexpr array
    name = input_file.replace("\\", "/").split("/")[-1].replace(".", "_")
    print(f"// Reference CRC32 values for {input_file}")
    print(f"// Generated by gen_reference_crcs.py using ffmpeg {width}x{height}")
    print(f"// {len(crcs)} frames")
    print(f"inline constexpr uint32_t cRefCrc_{name}[] = {{")
    for i, crc in enumerate(crcs):
        suffix = "," if i < len(crcs) - 1 else ""
        print(f"    0x{crc:08x}{suffix}  // frame {i}")
    print("};")


if __name__ == "__main__":
    main()
