/** Sub0h264 — Frame output verification
 *
 *  CRC32 and PSNR-based verification of decoded frame output.
 *  CRC provides fast exact-match validation against ffmpeg reference.
 *  PSNR provides tolerance for algorithm variants (e.g. different
 *  deblocking approaches that aren't numerically identical).
 *
 *  Reference CRC values generated by scripts/gen_reference_crcs.py
 *  using ffmpeg decode of the same H.264 test vectors.
 *
 *  SPDX-License-Identifier: MIT
 */
#ifndef CROG_SUB0H264_FRAME_VERIFY_HPP
#define CROG_SUB0H264_FRAME_VERIFY_HPP

#include "frame.hpp"

#include <cstdint>
#include <cmath>

namespace sub0h264 {

// ── CRC32 — fast exact-match verification ───────────────────────────────

/** CRC32 lookup table (IEEE 802.3 polynomial, same as zlib/ESP ROM). */
inline constexpr uint32_t crc32Table(uint32_t idx) noexcept
{
    uint32_t crc = idx;
    for (uint32_t j = 0U; j < 8U; ++j)
        crc = (crc >> 1U) ^ (0xEDB88320U & (-(crc & 1U)));
    return crc;
}

/** Compute CRC32 over a byte buffer (matches zlib.crc32 / esp_rom_crc32_le). */
inline uint32_t crc32(uint32_t init, const uint8_t* data, uint32_t len) noexcept
{
    uint32_t crc = init ^ 0xFFFFFFFFU;
    for (uint32_t i = 0U; i < len; ++i)
        crc = (crc >> 8U) ^ crc32Table((crc ^ data[i]) & 0xFFU);
    return crc ^ 0xFFFFFFFFU;
}

/** Compute stride-aware CRC32 over an I420 frame (Y + U + V planes).
 *
 *  Processes each row individually to exclude stride padding bytes.
 *  This matches the NestNinja validation approach and produces
 *  identical CRC values to Python's zlib.crc32.
 *
 *  @param frame  Decoded frame
 *  @return CRC32 value
 */
inline uint32_t frameCrc32(const Frame& frame) noexcept
{
    uint32_t crc = 0U;

    // Y plane: height rows × width bytes
    for (uint32_t r = 0U; r < frame.height(); ++r)
        crc = crc32(crc, frame.yRow(r), frame.width());

    // U plane: height/2 rows × width/2 bytes
    uint32_t chromaH = frame.height() / 2U;
    uint32_t chromaW = frame.width() / 2U;
    for (uint32_t r = 0U; r < chromaH; ++r)
        crc = crc32(crc, frame.uRow(r), chromaW);

    // V plane: height/2 rows × width/2 bytes
    for (uint32_t r = 0U; r < chromaH; ++r)
        crc = crc32(crc, frame.vRow(r), chromaW);

    return crc;
}

// ── PSNR — tolerance-based comparison ───────────────────────────────────

/** Compute PSNR (Peak Signal-to-Noise Ratio) between two frames.
 *
 *  PSNR = 10 * log10(MAX^2 / MSE) where MAX=255 for 8-bit.
 *  Returns infinity for identical frames, >40 dB for very good match,
 *  >30 dB for acceptable match, <20 dB for significant differences.
 *
 *  Compares Y plane only (luma PSNR is the most meaningful for H.264).
 *
 *  @param a  First frame
 *  @param b  Second frame (must have same dimensions)
 *  @return PSNR in dB, or 999.0 for identical frames
 */
inline double framePsnr(const Frame& a, const Frame& b) noexcept
{
    if (a.width() != b.width() || a.height() != b.height())
        return 0.0;

    uint64_t sse = 0U;
    for (uint32_t row = 0U; row < a.height(); ++row)
    {
        const uint8_t* ra = a.yRow(row);
        const uint8_t* rb = b.yRow(row);
        for (uint32_t col = 0U; col < a.width(); ++col)
        {
            int32_t diff = static_cast<int32_t>(ra[col]) - static_cast<int32_t>(rb[col]);
            sse += static_cast<uint64_t>(diff * diff);
        }
    }

    if (sse == 0U)
        return 999.0; // Identical

    uint32_t numPixels = a.width() * a.height();
    double mse = static_cast<double>(sse) / numPixels;
    /// Peak value for 8-bit samples — ITU-T H.264 uses 8-bit depth.
    static constexpr double cPeakValue = 255.0;
    return 10.0 * std::log10((cPeakValue * cPeakValue) / mse);
}

// ── Reference CRC values ────────────────────────────────────────────────
// Generated by scripts/gen_reference_crcs.py using ffmpeg decode.

/// Baseline CAVLC 640x480 short (50 frames).
/// Source: ffmpeg 8.0.1 decode of baseline_640x480_short.h264
inline constexpr uint32_t cRefCrcBaseline[] = {
    0x62f18fa1U, 0xd95c8c09U, 0x0f19ccdbU, 0x4c6ead40U, 0x558fcc2fU,
    0x656b71a6U, 0x15e15625U, 0x88b30ef0U, 0x5a50f1bcU, 0x8e48fbacU,
    0xc739bc98U, 0x85ace076U, 0xd4d6ec98U, 0x2320108dU, 0x1f342ff9U,
    0xfc11d6c0U, 0xd6f3a29eU, 0x45d83578U, 0xdddff8afU, 0xf1bb0b30U,
    0x5ba1526bU, 0xcee51d95U, 0x71cba0dbU, 0x2cc4abedU, 0x720a7d7fU,
    0x6adfc89aU, 0x22d41009U, 0x22f45d31U, 0xf31a3671U, 0xd3355a59U,
    0xc5165f6aU, 0x0cf736f8U, 0x04189f24U, 0xffcc2ac1U, 0xe734eee9U,
    0xbcc56b8eU, 0x63414ff1U, 0x4d3b4ea9U, 0xbfb380fdU, 0x74d0063bU,
    0x2b483a07U, 0xf591d4c8U, 0x986a5792U, 0x8f62c790U, 0x4cbb9d89U,
    0x07cdc489U, 0x7c13fb59U, 0xefbc87d3U, 0xd4e43be8U, 0x551b8af3U,
};

/// Flat black 640x480 (first 5 frames — all identical for all-black content).
/// Source: ffmpeg 8.0.1 decode of flat_black_640x480.h264
inline constexpr uint32_t cRefCrcFlatBlack[] = {
    0x509df05fU, 0x509df05fU, 0x509df05fU, 0x509df05fU, 0x509df05fU,
};

/// High CABAC 640x480 (first 5 frames).
/// Source: ffmpeg 8.0.1 decode of high_640x480.h264
inline constexpr uint32_t cRefCrcHigh[] = {
    0x4b0b900cU, 0x6c9a4598U, 0x273c8369U, 0xb7cb7ce2U, 0x80b5b382U,
};

/// Number of reference CRC entries for each fixture.
inline constexpr uint32_t cRefCrcBaselineCount = sizeof(cRefCrcBaseline) / sizeof(cRefCrcBaseline[0]);
inline constexpr uint32_t cRefCrcFlatBlackCount = sizeof(cRefCrcFlatBlack) / sizeof(cRefCrcFlatBlack[0]);
inline constexpr uint32_t cRefCrcHighCount = sizeof(cRefCrcHigh) / sizeof(cRefCrcHigh[0]);

} // namespace sub0h264

#endif // CROG_SUB0H264_FRAME_VERIFY_HPP
